### ISSUE TITLE
vampeta

### ISSUE THREAD

**Issue by GuilhermeGraeff** [marcosgregorio/trabalho_algoritmo#1]
![image](https://github.com/marcosgregorio/POD-UFFS/assets/48657331/28fb19f7-2a71-4c5e-b094-3b015e903fb2)

**Comment by marcosgregorio** [comment]
![image](https://github.com/marcosgregorio/trabalho_algoritmo/assets/78617642/7fd5b324-dd2d-484c-94d9-8f4e0cd8c801)
